### ISSUE TITLE
Shaders fail in the end dimension (complementary v4.2 dev2)

### ISSUE THREAD

**Issue by HeartlessAUS** [IrisShaders/Iris#665]
### What happened?

A bug happened! (keeping this as a meme)
Using Complementary Shaders v4.2 Development Version 2 (Available via complementary discord)

~~Lightshafts, Fog, and Emmisives fail to work in the end dimension~~
Judging from log posted, it seems everything fails in the end, and reverts to default

previous development version works with no issues (v4.2 Development Version 1)

### Screenshots

![2021-07-30_15 09 45](https://user-images.githubusercontent.com/47524314/127603807-de891955-7d29-4594-9548-a3dc83cd2946.png)
![2021-07-30_15 11 27](https://user-images.githubusercontent.com/47524314/127603821-e44bd1e8-76bc-42f8-ba91-04277980858d.png)

### Relevant log output

```shell
[15:15:09] [Render thread/WARN]: Ignoring draw buffer 9 from draw buffers array [0, 5, 9] since Iris doesn't support extended color buffers yet.
[15:15:09] [Render thread/WARN]: Shader compilation log for composite.fsh: 0(1469) : error C1503: undefined variable "cloudThickness"
0(1469) : error C1503: undefined variable "cloudAltitude"
0(1469) : error C1503: undefined variable "cloudThickness"
0(1518) : error C1503: undefined variable "invCloudAmount"
0(1520) : error C1503: undefined variable "cloudUpColor"

[15:15:09] [Render thread/ERROR]: Couldn't load NewWorldRenderingPipeline, falling back to vanilla shaders.
java.lang.RuntimeException: Shader compilation failed!
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:212) ~[iris-mc1.17-1.1.1.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.<init>(CompositeRenderer.java:80) ~[iris-mc1.17-1.1.1.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:190) ~[iris-mc1.17-1.1.1.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:421) ~[iris-mc1.17-1.1.1.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:39) [iris-mc1.17-1.1.1.jar:?]
	at net.minecraft.class_761.handler$cdm000$iris$beginWorldRender(class_761.java:8807) [intermediary-1.17.1.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java) [intermediary-1.17.1.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1026) [intermediary-1.17.1.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:810) [intermediary-1.17.1.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1112) [intermediary-1.17.1.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
Caused by: java.lang.RuntimeException: Failed to compile FRAGMENT shader for program composite.fsh
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:97) ~[iris-mc1.17-1.1.1.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:68) ~[iris-mc1.17-1.1.1.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:208) ~[iris-mc1.17-1.1.1.jar:?]
	... 18 more
Caused by: java.lang.RuntimeException: Shader compilation failed, see log for details
	at net.coderbot.iris.gl.shader.GlShader.createShader(GlShader.java:44) ~[iris-mc1.17-1.1.1.jar:?]
	at net.coderbot.iris.gl.shader.GlShader.<init>(GlShader.java:23) ~[iris-mc1.17-1.1.1.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:95) ~[iris-mc1.17-1.1.1.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:68) ~[iris-mc1.17-1.1.1.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:208) ~[iris-mc1.17-1.1.1.jar:?]
	... 18 more
[15:15:10] [Render thread/INFO]: Stopping worker threads
[15:15:10] [Render thread/INFO]: Started 12 worker threads
[15:15:10] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ModelViewMatrix
[15:15:10] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ProjectionMatrix
[15:15:10] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_NormalMatrix
[15:15:10] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ModelViewMatrix
[15:15:10] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ProjectionMatrix
[15:15:10] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_NormalMatrix
[15:15:10] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ModelViewMatrix
[15:15:10] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ProjectionMatrix
[15:15:10] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_NormalMatrix
[15:15:10] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ModelViewMatrix
[15:15:10] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ProjectionMatrix
[15:15:10] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_NormalMatrix
[15:15:10] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ModelViewMatrix
[15:15:10] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ProjectionMatrix
[15:15:10] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_NormalMatrix
```

### Iris and Minecraft Version

iris-mc1.17-1.1.1.jar for 1.17

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

Nvidia RTX 2070

### Java Version

Java 16

**Comment by HeartlessAUS** [comment]
issue was resolved by removing VL_CLOUDS in common.glsl ONLY in the end
```
  #ifdef END
    #undef LENS_FLARE
	#undef VL_CLOUDS
  #endif
```
