### ISSUE TITLE
BSL shaders wont load in game

### ISSUE THREAD

**Issue by gutt3rsn1pe** [IrisShaders/Iris#2821]
### Minecraft Version

1.20.4

### Iris Version

1.20.4

### Sodium Version

1.20.4

### Operating System

Windows 11

### What is your GPU?

NVIDIA Gforce RTX 3060 Ti

### Java Version

1.8.0

### Reproduction Steps

when I join the game the shaders won't load in, instead I get this message instead 

deferred.fsh: deferred.fsh: 0(54) : error C7537: OpenGL does not allow 'sample' after a type specifier
0(54) : error C0000: syntax error, unexpected '=', expecting ';' or '(' at token "="
0(55) : error C0000: syntax error, unexpected ',', expecting "::" at token ","
0(56) : error C0000: syntax error, unexpected '-', expecting "::" at token "-"

### Crash Report file and latest.log

```shell

```

**Comment by SuperLavaHair1** [comment]
uhh, it REALLY sounds like an issue with my shaders when i updated to 1.21. perhaps download the shader that was MEANT for that specific version?

**Comment by winapiadmin** [comment]
can you post the full latest.log, and crash report file (if exists)? also try redownloading the shader if you didn't modify it
