### ISSUE TITLE
BSL and complimentary not working with Iris 1.17.1

### ISSUE THREAD

**Issue by topbun92** [IrisShaders/Iris#700]
### What happened?

Only shaders i can seem to get "working" are sildurs enhanced defaults. but BSL and Complimentary are supposed to be supported and they don't start at all. 

### Relevant log output

```shell
[20:22:31] [Render thread/ERROR]: Couldn't load NewWorldRenderingPipeline, falling back to vanilla shaders.
java.lang.RuntimeException: Shader compilation failed!
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:208) ~[iris-mc1.17-1.1.2-starline+build.457.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.<init>(CompositeRenderer.java:76) ~[iris-mc1.17-1.1.2-starline+build.457.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:185) ~[iris-mc1.17-1.1.2-starline+build.457.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:418) ~[iris-mc1.17-1.1.2-starline+build.457.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:39) [iris-mc1.17-1.1.2-starline+build.457.jar:?]
	at net.minecraft.class_761.handler$daj000$iris$beginWorldRender(class_761.java:11309) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1026) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:810) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1112) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-minecraft-1.17.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Failed to compile VERTEX shader for program deferred.vsh
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:97) ~[iris-mc1.17-1.1.2-starline+build.457.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:60) ~[iris-mc1.17-1.1.2-starline+build.457.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:204) ~[iris-mc1.17-1.1.2-starline+build.457.jar:?]
	... 26 more
Caused by: java.lang.RuntimeException: Shader compilation failed, see log for details
	at net.coderbot.iris.gl.shader.GlShader.createShader(GlShader.java:44) ~[iris-mc1.17-1.1.2-starline+build.457.jar:?]
	at net.coderbot.iris.gl.shader.GlShader.<init>(GlShader.java:23) ~[iris-mc1.17-1.1.2-starline+build.457.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:95) ~[iris-mc1.17-1.1.2-starline+build.457.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:60) ~[iris-mc1.17-1.1.2-starline+build.457.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:204) ~[iris-mc1.17-1.1.2-starline+build.457.jar:?]
	... 26 more
[20:22:31] [Render thread/INFO]: Stopping worker threads
[20:22:31] [Render thread/INFO]: Started 24 worker threads
[20:22:31] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ModelViewMatrix
[20:22:31] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ProjectionMatrix
[20:22:31] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_NormalMatrix
[20:22:31] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ModelViewMatrix
[20:22:31] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ProjectionMatrix
[20:22:31] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_NormalMatrix
[20:22:31] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ModelViewMatrix
[20:22:31] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ProjectionMatrix
[20:22:31] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_NormalMatrix
[20:22:31] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ModelViewMatrix
[20:22:31] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ProjectionMatrix
[20:22:31] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_NormalMatrix
[20:22:31] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ModelViewMatrix
[20:22:31] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ProjectionMatrix
[20:22:31] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_NormalMatrix
```

### Iris and Minecraft Version

iris 1.1.1, MC 1.17.1, Fabric 11.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Win 10

### What is your GPU?

RTX3080

### Java Version

Java 16

**Comment by IMS212** [comment]
Can you post the full log file?

**Comment by Birmioh** [comment]
Hello, that's working great for me on 1.17.1 as you can see[](https://i.goopics.net/rv8nw.png) i'm using:
Iris: 1.1.1
Fabric: 0.11.6
Complementary: 4.1

It seems you are using 1.1.2 version on iris, try the 1.1.1, 
BSL also working with the 8.* version

**Comment by topbun92** [comment]
sorry, the log i posted was with the starline fork. the issue is with both normal and starline. the normal iris is the 1.1.1 and the log is as follows (from the moment i toggle the shaders on)

[23:48:56] [Render thread/INFO]: Using shaderpack: ComplementaryShaders_v4.1.zip
[23:48:56] [Render thread/INFO]: [CHAT] Toggled shaders to ComplementaryShaders_v4.1.zip!
[23:48:56] [Render thread/WARN]: Shader compilation log for deferred.vsh: 0(874) : error C0105: Syntax error in #if

[23:48:56] [Render thread/ERROR]: Couldn't load NewWorldRenderingPipeline, falling back to vanilla shaders.
java.lang.RuntimeException: Shader compilation failed!
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:212) ~[iris-mc1.17-1.1.1.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.<init>(CompositeRenderer.java:80) ~[iris-mc1.17-1.1.1.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:185) ~[iris-mc1.17-1.1.1.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:421) ~[iris-mc1.17-1.1.1.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:39) [iris-mc1.17-1.1.1.jar:?]
	at net.minecraft.class_761.handler$dah000$iris$beginWorldRender(class_761.java:11307) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1026) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:810) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1112) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-minecraft-1.17.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Failed to compile VERTEX shader for program deferred.vsh
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:97) ~[iris-mc1.17-1.1.1.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:60) ~[iris-mc1.17-1.1.1.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:208) ~[iris-mc1.17-1.1.1.jar:?]
	... 26 more
Caused by: java.lang.RuntimeException: Shader compilation failed, see log for details
	at net.coderbot.iris.gl.shader.GlShader.createShader(GlShader.java:44) ~[iris-mc1.17-1.1.1.jar:?]
	at net.coderbot.iris.gl.shader.GlShader.<init>(GlShader.java:23) ~[iris-mc1.17-1.1.1.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:95) ~[iris-mc1.17-1.1.1.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:60) ~[iris-mc1.17-1.1.1.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:208) ~[iris-mc1.17-1.1.1.jar:?]
	... 26 more
[23:48:56] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ModelViewMatrix
[23:48:56] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ProjectionMatrix
[23:48:56] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_NormalMatrix
[23:48:56] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ModelViewMatrix
[23:48:56] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ProjectionMatrix
[23:48:56] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_NormalMatrix
[23:48:56] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ModelViewMatrix
[23:48:56] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ProjectionMatrix
[23:48:56] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_NormalMatrix
[23:48:56] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ModelViewMatrix
[23:48:56] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ProjectionMatrix
[23:48:56] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_NormalMatrix
[23:48:56] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ModelViewMatrix
[23:48:56] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_ProjectionMatrix
[23:48:56] [Render thread/INFO]: [STDERR]: No uniform exists with name: u_NormalMatrix
[23:49:03] [Server thread/INFO]: Saving and pausing game...
[23:49:03] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[23:49:03] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[23:49:03] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end

**Comment by AlsoNiko** [comment]
Please send the log file itself, not a cherry picked part of it

**Comment by topbun92** [comment]
only "cherry picked" b/c nothing else seemed relevant so my apologies. it was just the fabric boot sequence that didn't throw any other errors. at any rate, after systematically removing and re-adding every mod one by one i literally just pinpointed it to an incompatibility with the "version changer" mod which, as it happens, i no longer use so its all good
