### ISSUE TITLE
[Regression] Distant Horizons shader compilation fails with "unexpected IDENTIFIER" on Iris 1.11.4 (Photon Shader)

### ISSUE THREAD

**Issue by annhilati** [IrisShaders/Iris#3355]
### What happened?

When using the Photon shaderpack with Distant Horizons, shader compilation fails for `dh_terrain.fsh` on Iris 1.11.4. This setup worked perfectly on Iris 1.11.2. 

The OpenGL compiler reports a syntax error. Testing indicates that the `TransformPatcher` in Iris 1.11.4 is generating invalid GLSL when applying DH compatibility modifications to Photon.

### Log output

```text
Shader compilation log for dh_terrain.fsh: ERROR: 0:49: '' :  syntax error, unexpected IDENTIFIER
ERROR: 1 compilation errors.  No code generated.
```

### Minecraft Version

26.2

### Iris Version

1.11.4

### Operating System

Windows 11

### What is your GPU?

AMD Radeon RX 6950 XT

### Additional context

- **Working setup:** Sodium 0.9.1 + Iris 1.11.2 + DH 3.2.0
- **Failing setup:** Sodium 0.9.2 + Iris 1.11.4 + DH 3.2.0
- *Note:* DH 3.3.0 crashes completely with a `NoSuchMethodError: isReverseZDuringShaders()` on Iris 1.11.4, which is why DH 3.2.0 was used for this test.
- Testing showed that the line number (`0:49`) reported by the driver does not shift when lines are manually added to `dh_terrain.fsh`, which implies the syntax error is occurring within the header/injections generated by Iris.
